
clear all; close all
clc

%% parameter settings



Trial = 100; % trial times

        fontsizet = 24;
        fontsizea = 18;
        fontsizel = 36;


M = 100; N = 1500;

% matrix dimension M-by-N
minK = 5; maxK = 35; inter = 2;
addon = minK - 2;
I = (maxK-minK+2)/2;



% ----------------Set 1---------------
F = 4;

parfor i = 1:I            
    [SucRateAIHT(i),SucRateL1(i),SucRateLp(i),SucRateTL1(i),SucRateL12(i),SucRateMCP(i),SucRateSPB(i),MSEAIHT(i),MSEL1(i),MSELp(i),MSETL1(i),MSEL12(i),MSEMCP(i),MSESPB(i)] = noisefreetestonoverDCTforPC(i,M,N,F,Trial,addon)
end

axes('position',[0.04,0.55,0.3,.4]),
plot(minK:inter:maxK,SucRateAIHT,'-d','LineWidth',1.2,'MarkerSize',16), hold on,...
    plot(minK:inter:maxK,SucRateL1,'-o','LineWidth',1.25,'MarkerSize',16), hold on,...
    plot(minK:inter:maxK,SucRateLp,'-s','LineWidth',1.8,'MarkerSize',20),...
    plot(minK:inter:maxK,SucRateTL1,'-<','LineWidth',1.2,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateL12,'-^','LineWidth',1.25,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateMCP,'-*','LineWidth',1.25,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateSPB,'--p','LineWidth',1.5,'MarkerSize',18),...
    set(gca, 'fontsize', fontsizea),
    title('$\mathbf{F=4}$','interpreter','latex','FontSize',fontsizet),
    ylabel('success rate','interpreter','latex','FontSize',fontsizel), set(legend('AIHT','ADMM-$\ell_1$','IRLS-$\ell_p$','DCA-TL1','DCA-$\ell_{1-2}$','DCA-MCP','Springback'),'interpreter','latex','fontsize',15), box on


% ----------------Set 2---------------
F = 6;
    
parfor i = 1:I            
    [SucRateAIHT(i),SucRateL1(i),SucRateLp(i),SucRateTL1(i),SucRateL12(i),SucRateMCP(i),SucRateSPB(i),MSEAIHT(i),MSEL1(i),MSELp(i),MSETL1(i),MSEL12(i),MSEMCP(i),MSESPB(i)] = noisefreetestonoverDCTforPC(i,M,N,F,Trial,addon)
end

 axes('position',[0.365,0.55,0.3,.4]),
plot(minK:inter:maxK,SucRateAIHT,'-d','LineWidth',1.2,'MarkerSize',16), hold on,...
    plot(minK:inter:maxK,SucRateL1,'-o','LineWidth',1.25,'MarkerSize',16), hold on,...
    plot(minK:inter:maxK,SucRateLp,'-s','LineWidth',1.8,'MarkerSize',20),...
    plot(minK:inter:maxK,SucRateTL1,'-<','LineWidth',1.2,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateL12,'-^','LineWidth',1.25,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateMCP,'-*','LineWidth',1.25,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateSPB,'--p','LineWidth',1.5,'MarkerSize',18),...
    set(gca, 'fontsize', fontsizea),
    title('$\mathbf{F=6}$','interpreter','latex','FontSize',fontsizet),
set(legend('AIHT','ADMM-$\ell_1$','IRLS-$\ell_p$','DCA-TL1','DCA-$\ell_{1-2}$','DCA-MCP','Springback'),'interpreter','latex','fontsize',15), box on
    
% ----------------Set 3---------------
F = 8;
   
parfor i = 1:I            
    [SucRateAIHT(i),SucRateL1(i),SucRateLp(i),SucRateTL1(i),SucRateL12(i),SucRateMCP(i),SucRateSPB(i),MSEAIHT(i),MSEL1(i),MSELp(i),MSETL1(i),MSEL12(i),MSEMCP(i),MSESPB(i)] = noisefreetestonoverDCTforPC(i,M,N,F,Trial,addon)
end

axes('position',[0.69,0.55,0.3,.4]),
plot(minK:inter:maxK,SucRateAIHT,'-d','LineWidth',1.2,'MarkerSize',16), hold on,...
    plot(minK:inter:maxK,SucRateL1,'-o','LineWidth',1.25,'MarkerSize',16), hold on,...
    plot(minK:inter:maxK,SucRateLp,'-s','LineWidth',1.8,'MarkerSize',20),...
    plot(minK:inter:maxK,SucRateTL1,'-<','LineWidth',1.2,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateL12,'-^','LineWidth',1.25,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateMCP,'-*','LineWidth',1.25,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateSPB,'--p','LineWidth',1.5,'MarkerSize',18),...
    set(gca, 'fontsize', fontsizea),
    title('$\mathbf{F=8}$','interpreter','latex','FontSize',fontsizet),
set(legend('AIHT','ADMM-$\ell_1$','IRLS-$\ell_p$','DCA-TL1','DCA-$\ell_{1-2}$','DCA-MCP','Springback'),'interpreter','latex','fontsize',15), box on
    
% ----------------Set 4---------------
F = 10;
    
parfor i = 1:I
    [SucRateAIHT(i),SucRateL1(i),SucRateLp(i),SucRateTL1(i),SucRateL12(i),SucRateMCP(i),SucRateSPB(i),MSEAIHT(i),MSEL1(i),MSELp(i),MSETL1(i),MSEL12(i),MSEMCP(i),MSESPB(i)] = noisefreetestonoverDCTforPC(i,M,N,F,Trial,addon)
end

axes('position',[0.04,0.07,0.3,.4]),
plot(minK:inter:maxK,SucRateAIHT,'-d','LineWidth',1.2,'MarkerSize',16), hold on,...
    plot(minK:inter:maxK,SucRateL1,'-o','LineWidth',1.25,'MarkerSize',16), hold on,...
    plot(minK:inter:maxK,SucRateLp,'-s','LineWidth',1.8,'MarkerSize',20),...
    plot(minK:inter:maxK,SucRateTL1,'-<','LineWidth',1.2,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateL12,'-^','LineWidth',1.25,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateMCP,'-*','LineWidth',1.25,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateSPB,'--p','LineWidth',1.5,'MarkerSize',18),...
    set(gca, 'fontsize', fontsizea),
    title('$\mathbf{F=10}$','interpreter','latex','FontSize',fontsizet), 
    xlabel('sparsity $s$','interpreter','latex','FontSize',fontsizel),...
    ylabel('success rate','interpreter','latex','FontSize',fontsizel), 
    set(legend('AIHT','ADMM-$\ell_1$','IRLS-$\ell_p$','DCA-TL1','DCA-$\ell_{1-2}$','DCA-MCP','Springback'),'interpreter','latex','fontsize',15), box on


% ----------------Set 5---------------
F = 12;
   
parfor i = 1:I
    [SucRateAIHT(i),SucRateL1(i),SucRateLp(i),SucRateTL1(i),SucRateL12(i),SucRateMCP(i),SucRateSPB(i),MSEAIHT(i),MSEL1(i),MSELp(i),MSETL1(i),MSEL12(i),MSEMCP(i),MSESPB(i)] = noisefreetestonoverDCTforPC(i,M,N,F,Trial,addon)
end

axes('position',[0.365,0.07,0.3,.4]),
plot(minK:inter:maxK,SucRateAIHT,'-d','LineWidth',1.2,'MarkerSize',16), hold on,...
    plot(minK:inter:maxK,SucRateL1,'-o','LineWidth',1.25,'MarkerSize',16), hold on,...
    plot(minK:inter:maxK,SucRateLp,'-s','LineWidth',1.8,'MarkerSize',20),...
    plot(minK:inter:maxK,SucRateTL1,'-<','LineWidth',1.2,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateL12,'-^','LineWidth',1.25,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateMCP,'-*','LineWidth',1.25,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateSPB,'--p','LineWidth',1.5,'MarkerSize',18),...
    set(gca, 'fontsize', fontsizea),
    title('$\mathbf{F=12}$','interpreter','latex','FontSize',fontsizet), 
    xlabel('sparsity $s$','interpreter','latex','FontSize',fontsizel),...
    set(legend('AIHT','ADMM-$\ell_1$','IRLS-$\ell_p$','DCA-TL1','DCA-$\ell_{1-2}$','DCA-MCP','Springback'),'interpreter','latex','fontsize',15), box on



% ----------------Set 6---------------
F = 16;
   
parfor i = 1:I
    [SucRateAIHT(i),SucRateL1(i),SucRateLp(i),SucRateTL1(i),SucRateL12(i),SucRateMCP(i),SucRateSPB(i),MSEAIHT(i),MSEL1(i),MSELp(i),MSETL1(i),MSEL12(i),MSEMCP(i),MSESPB(i)] = noisefreetestonoverDCTforPC(i,M,N,F,Trial,addon)
end

axes('position',[0.69,0.07,0.3,.4]),
plot(minK:inter:maxK,SucRateAIHT,'-d','LineWidth',1.2,'MarkerSize',16), hold on,...
    plot(minK:inter:maxK,SucRateL1,'-o','LineWidth',1.25,'MarkerSize',16), hold on,...
    plot(minK:inter:maxK,SucRateLp,'-s','LineWidth',1.8,'MarkerSize',20),...
    plot(minK:inter:maxK,SucRateTL1,'-<','LineWidth',1.2,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateL12,'-^','LineWidth',1.25,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateMCP,'-*','LineWidth',1.25,'MarkerSize',16),...
    plot(minK:inter:maxK,SucRateSPB,'--p','LineWidth',1.5,'MarkerSize',18),...
    set(gca, 'fontsize', fontsizea),
    title('$\mathbf{F=16}$','interpreter','latex','FontSize',fontsizet),
    xlabel('sparsity $s$','interpreter','latex','FontSize',fontsizel),...
    set(legend('AIHT','ADMM-$\ell_1$','IRLS-$\ell_p$','DCA-TL1','DCA-$\ell_{1-2}$','DCA-MCP','Springback'),'interpreter','latex','fontsize',15), box on


